/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Backtest {
  'id' : bigint,
  'userId' : Principal,
  'createdAt' : Time,
  'results' : string,
  'updatedAt' : [] | [Time],
  'performance' : string,
  'strategyId' : bigint,
}
export interface Position {
  'id' : bigint,
  'portfolioId' : bigint,
  'signalStrength' : SignalStrength,
  'asset' : string,
  'userId' : Principal,
  'takeProfit' : [] | [number],
  'sellPrice' : [] | [number],
  'stopLoss' : [] | [number],
  'buyPrice' : number,
  'quantity' : number,
}
export interface ReadyToDumpSignal {
  'id' : bigint,
  'stopLossZone' : number,
  'entryZone' : number,
  'signalStrength' : SignalStrength,
  'timeframe' : string,
  'createdAt' : Time,
  'takeProfitZone' : number,
  'confidenceScore' : number,
  'updatedAt' : [] | [Time],
  'symbol' : string,
}
export interface Settings {
  'enableToastNotifications' : boolean,
  'displayUiTheme' : string,
  'riskTolerance' : number,
  'enableTimeframeSync' : boolean,
  'preferredTimeframes' : Array<string>,
  'confidenceLevel' : number,
  'alertThreshold' : number,
  'enableAudioAlerts' : boolean,
  'aiForecastSensitivity' : number,
  'enablePerformanceMode' : boolean,
  'enableBrowserNotifications' : boolean,
}
export type SignalStrength = { 'buy' : null } |
  { 'strongBuy' : null } |
  { 'hold' : null } |
  { 'sell' : null } |
  { 'strongSell' : null };
export interface Strategy {
  'id' : bigint,
  'code' : string,
  'userId' : [] | [Principal],
  'name' : string,
  'description' : string,
  'performance' : string,
}
export type Time = bigint;
export interface TradeJournalEntry {
  'id' : bigint,
  'pnl' : number,
  'exitTime' : [] | [Time],
  'entryTime' : Time,
  'userId' : Principal,
  'positionId' : bigint,
  'notes' : string,
  'outcome' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'riskTolerance' : [] | [number],
  'preferredTimeframe' : [] | [string],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBacktest' : ActorMethod<[bigint, string, string], bigint>,
  'createPosition' : ActorMethod<
    [bigint, string, number, number, SignalStrength],
    bigint
  >,
  'createReadyToDumpSignal' : ActorMethod<
    [string, string, SignalStrength, number, number, number, number],
    bigint
  >,
  'createStrategy' : ActorMethod<[string, string, string, string], bigint>,
  'createTradeJournalEntry' : ActorMethod<
    [bigint, string, string, [] | [Time], number],
    bigint
  >,
  'deleteBacktest' : ActorMethod<[bigint], undefined>,
  'deletePosition' : ActorMethod<[bigint], undefined>,
  'deleteReadyToDumpSignal' : ActorMethod<[bigint], undefined>,
  'deleteStrategy' : ActorMethod<[bigint], undefined>,
  'deleteTradeJournalEntry' : ActorMethod<[bigint], undefined>,
  'fetchCryptoDataFromBinance' : ActorMethod<[], string>,
  'getActiveReadyToDumpSignals' : ActorMethod<[], Array<ReadyToDumpSignal>>,
  'getAllBacktests' : ActorMethod<[], Array<Backtest>>,
  'getAllPositions' : ActorMethod<[], Array<Position>>,
  'getAllReadyToDumpSignals' : ActorMethod<[], Array<ReadyToDumpSignal>>,
  'getAllStrategies' : ActorMethod<[], Array<Strategy>>,
  'getAllTradeJournalEntries' : ActorMethod<[], Array<TradeJournalEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDefaultSettings' : ActorMethod<[], Settings>,
  'getPositionsByPortfolio' : ActorMethod<[bigint], Array<Position>>,
  'getStrategy' : ActorMethod<[bigint], [] | [Strategy]>,
  'getStrategyCode' : ActorMethod<[bigint], [] | [string]>,
  'getUserBacktests' : ActorMethod<[], Array<Backtest>>,
  'getUserPositions' : ActorMethod<[], Array<Position>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSettings' : ActorMethod<[], Settings>,
  'getUserStrategies' : ActorMethod<[], Array<Strategy>>,
  'getUserTradeJournalEntries' : ActorMethod<[], Array<TradeJournalEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetUserSettings' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserSettings' : ActorMethod<[Settings], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBacktest' : ActorMethod<[bigint, string, string], undefined>,
  'updatePosition' : ActorMethod<
    [bigint, [] | [number], [] | [number], [] | [number]],
    undefined
  >,
  'updateReadyToDumpSignal' : ActorMethod<
    [bigint, string, SignalStrength, number, number, number, number],
    undefined
  >,
  'updateStrategy' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateTradeJournalEntry' : ActorMethod<
    [bigint, string, string, [] | [Time], number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];