/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SignalStrength = IDL.Variant({
  'buy' : IDL.Null,
  'strongBuy' : IDL.Null,
  'hold' : IDL.Null,
  'sell' : IDL.Null,
  'strongSell' : IDL.Null,
});
export const Time = IDL.Int;
export const ReadyToDumpSignal = IDL.Record({
  'id' : IDL.Nat,
  'stopLossZone' : IDL.Float64,
  'entryZone' : IDL.Float64,
  'signalStrength' : SignalStrength,
  'timeframe' : IDL.Text,
  'createdAt' : Time,
  'takeProfitZone' : IDL.Float64,
  'confidenceScore' : IDL.Float64,
  'updatedAt' : IDL.Opt(Time),
  'symbol' : IDL.Text,
});
export const Backtest = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'results' : IDL.Text,
  'updatedAt' : IDL.Opt(Time),
  'performance' : IDL.Text,
  'strategyId' : IDL.Nat,
});
export const Position = IDL.Record({
  'id' : IDL.Nat,
  'portfolioId' : IDL.Nat,
  'signalStrength' : SignalStrength,
  'asset' : IDL.Text,
  'userId' : IDL.Principal,
  'takeProfit' : IDL.Opt(IDL.Float64),
  'sellPrice' : IDL.Opt(IDL.Float64),
  'stopLoss' : IDL.Opt(IDL.Float64),
  'buyPrice' : IDL.Float64,
  'quantity' : IDL.Float64,
});
export const Strategy = IDL.Record({
  'id' : IDL.Nat,
  'code' : IDL.Text,
  'userId' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'performance' : IDL.Text,
});
export const TradeJournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'pnl' : IDL.Float64,
  'exitTime' : IDL.Opt(Time),
  'entryTime' : Time,
  'userId' : IDL.Principal,
  'positionId' : IDL.Nat,
  'notes' : IDL.Text,
  'outcome' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'riskTolerance' : IDL.Opt(IDL.Float64),
  'preferredTimeframe' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const Settings = IDL.Record({
  'enableToastNotifications' : IDL.Bool,
  'displayUiTheme' : IDL.Text,
  'riskTolerance' : IDL.Float64,
  'enableTimeframeSync' : IDL.Bool,
  'preferredTimeframes' : IDL.Vec(IDL.Text),
  'confidenceLevel' : IDL.Float64,
  'alertThreshold' : IDL.Float64,
  'enableAudioAlerts' : IDL.Bool,
  'aiForecastSensitivity' : IDL.Float64,
  'enablePerformanceMode' : IDL.Bool,
  'enableBrowserNotifications' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBacktest' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createPosition' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, SignalStrength],
      [IDL.Nat],
      [],
    ),
  'createReadyToDumpSignal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        SignalStrength,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'createStrategy' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createTradeJournalEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(Time), IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'deleteBacktest' : IDL.Func([IDL.Nat], [], []),
  'deletePosition' : IDL.Func([IDL.Nat], [], []),
  'deleteReadyToDumpSignal' : IDL.Func([IDL.Nat], [], []),
  'deleteStrategy' : IDL.Func([IDL.Nat], [], []),
  'deleteTradeJournalEntry' : IDL.Func([IDL.Nat], [], []),
  'fetchCryptoDataFromBinance' : IDL.Func([], [IDL.Text], []),
  'getActiveReadyToDumpSignals' : IDL.Func(
      [],
      [IDL.Vec(ReadyToDumpSignal)],
      ['query'],
    ),
  'getAllBacktests' : IDL.Func([], [IDL.Vec(Backtest)], ['query']),
  'getAllPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
  'getAllReadyToDumpSignals' : IDL.Func(
      [],
      [IDL.Vec(ReadyToDumpSignal)],
      ['query'],
    ),
  'getAllStrategies' : IDL.Func([], [IDL.Vec(Strategy)], ['query']),
  'getAllTradeJournalEntries' : IDL.Func(
      [],
      [IDL.Vec(TradeJournalEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDefaultSettings' : IDL.Func([], [Settings], ['query']),
  'getPositionsByPortfolio' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Position)],
      ['query'],
    ),
  'getStrategy' : IDL.Func([IDL.Nat], [IDL.Opt(Strategy)], ['query']),
  'getStrategyCode' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getUserBacktests' : IDL.Func([], [IDL.Vec(Backtest)], ['query']),
  'getUserPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([], [Settings], ['query']),
  'getUserStrategies' : IDL.Func([], [IDL.Vec(Strategy)], ['query']),
  'getUserTradeJournalEntries' : IDL.Func(
      [],
      [IDL.Vec(TradeJournalEntry)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetUserSettings' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserSettings' : IDL.Func([Settings], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBacktest' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updatePosition' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
      ],
      [],
      [],
    ),
  'updateReadyToDumpSignal' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        SignalStrength,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'updateStrategy' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateTradeJournalEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(Time), IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SignalStrength = IDL.Variant({
    'buy' : IDL.Null,
    'strongBuy' : IDL.Null,
    'hold' : IDL.Null,
    'sell' : IDL.Null,
    'strongSell' : IDL.Null,
  });
  const Time = IDL.Int;
  const ReadyToDumpSignal = IDL.Record({
    'id' : IDL.Nat,
    'stopLossZone' : IDL.Float64,
    'entryZone' : IDL.Float64,
    'signalStrength' : SignalStrength,
    'timeframe' : IDL.Text,
    'createdAt' : Time,
    'takeProfitZone' : IDL.Float64,
    'confidenceScore' : IDL.Float64,
    'updatedAt' : IDL.Opt(Time),
    'symbol' : IDL.Text,
  });
  const Backtest = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'results' : IDL.Text,
    'updatedAt' : IDL.Opt(Time),
    'performance' : IDL.Text,
    'strategyId' : IDL.Nat,
  });
  const Position = IDL.Record({
    'id' : IDL.Nat,
    'portfolioId' : IDL.Nat,
    'signalStrength' : SignalStrength,
    'asset' : IDL.Text,
    'userId' : IDL.Principal,
    'takeProfit' : IDL.Opt(IDL.Float64),
    'sellPrice' : IDL.Opt(IDL.Float64),
    'stopLoss' : IDL.Opt(IDL.Float64),
    'buyPrice' : IDL.Float64,
    'quantity' : IDL.Float64,
  });
  const Strategy = IDL.Record({
    'id' : IDL.Nat,
    'code' : IDL.Text,
    'userId' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'performance' : IDL.Text,
  });
  const TradeJournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'pnl' : IDL.Float64,
    'exitTime' : IDL.Opt(Time),
    'entryTime' : Time,
    'userId' : IDL.Principal,
    'positionId' : IDL.Nat,
    'notes' : IDL.Text,
    'outcome' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'riskTolerance' : IDL.Opt(IDL.Float64),
    'preferredTimeframe' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const Settings = IDL.Record({
    'enableToastNotifications' : IDL.Bool,
    'displayUiTheme' : IDL.Text,
    'riskTolerance' : IDL.Float64,
    'enableTimeframeSync' : IDL.Bool,
    'preferredTimeframes' : IDL.Vec(IDL.Text),
    'confidenceLevel' : IDL.Float64,
    'alertThreshold' : IDL.Float64,
    'enableAudioAlerts' : IDL.Bool,
    'aiForecastSensitivity' : IDL.Float64,
    'enablePerformanceMode' : IDL.Bool,
    'enableBrowserNotifications' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBacktest' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createPosition' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, SignalStrength],
        [IDL.Nat],
        [],
      ),
    'createReadyToDumpSignal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          SignalStrength,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'createStrategy' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createTradeJournalEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(Time), IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'deleteBacktest' : IDL.Func([IDL.Nat], [], []),
    'deletePosition' : IDL.Func([IDL.Nat], [], []),
    'deleteReadyToDumpSignal' : IDL.Func([IDL.Nat], [], []),
    'deleteStrategy' : IDL.Func([IDL.Nat], [], []),
    'deleteTradeJournalEntry' : IDL.Func([IDL.Nat], [], []),
    'fetchCryptoDataFromBinance' : IDL.Func([], [IDL.Text], []),
    'getActiveReadyToDumpSignals' : IDL.Func(
        [],
        [IDL.Vec(ReadyToDumpSignal)],
        ['query'],
      ),
    'getAllBacktests' : IDL.Func([], [IDL.Vec(Backtest)], ['query']),
    'getAllPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
    'getAllReadyToDumpSignals' : IDL.Func(
        [],
        [IDL.Vec(ReadyToDumpSignal)],
        ['query'],
      ),
    'getAllStrategies' : IDL.Func([], [IDL.Vec(Strategy)], ['query']),
    'getAllTradeJournalEntries' : IDL.Func(
        [],
        [IDL.Vec(TradeJournalEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDefaultSettings' : IDL.Func([], [Settings], ['query']),
    'getPositionsByPortfolio' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Position)],
        ['query'],
      ),
    'getStrategy' : IDL.Func([IDL.Nat], [IDL.Opt(Strategy)], ['query']),
    'getStrategyCode' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
    'getUserBacktests' : IDL.Func([], [IDL.Vec(Backtest)], ['query']),
    'getUserPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([], [Settings], ['query']),
    'getUserStrategies' : IDL.Func([], [IDL.Vec(Strategy)], ['query']),
    'getUserTradeJournalEntries' : IDL.Func(
        [],
        [IDL.Vec(TradeJournalEntry)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetUserSettings' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserSettings' : IDL.Func([Settings], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBacktest' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updatePosition' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
        ],
        [],
        [],
      ),
    'updateReadyToDumpSignal' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          SignalStrength,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'updateStrategy' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateTradeJournalEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(Time), IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };