/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Settings {
    enableToastNotifications: boolean;
    displayUiTheme: string;
    riskTolerance: number;
    enableTimeframeSync: boolean;
    preferredTimeframes: Array<string>;
    confidenceLevel: number;
    alertThreshold: number;
    enableAudioAlerts: boolean;
    aiForecastSensitivity: number;
    enablePerformanceMode: boolean;
    enableBrowserNotifications: boolean;
}
export interface Position {
    id: bigint;
    portfolioId: bigint;
    signalStrength: SignalStrength;
    asset: string;
    userId: Principal;
    takeProfit?: number;
    sellPrice?: number;
    stopLoss?: number;
    buyPrice: number;
    quantity: number;
}
export interface TradeJournalEntry {
    id: bigint;
    pnl: number;
    exitTime?: Time;
    entryTime: Time;
    userId: Principal;
    positionId: bigint;
    notes: string;
    outcome: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Backtest {
    id: bigint;
    userId: Principal;
    createdAt: Time;
    results: string;
    updatedAt?: Time;
    performance: string;
    strategyId: bigint;
}
export interface Strategy {
    id: bigint;
    code: string;
    userId?: Principal;
    name: string;
    description: string;
    performance: string;
}
export interface ReadyToDumpSignal {
    id: bigint;
    stopLossZone: number;
    entryZone: number;
    signalStrength: SignalStrength;
    timeframe: string;
    createdAt: Time;
    takeProfitZone: number;
    confidenceScore: number;
    updatedAt?: Time;
    symbol: string;
}
export interface UserProfile {
    riskTolerance?: number;
    preferredTimeframe?: string;
    name: string;
}
export enum SignalStrength {
    buy = "buy",
    strongBuy = "strongBuy",
    hold = "hold",
    sell = "sell",
    strongSell = "strongSell"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBacktest(strategyId: bigint, performance: string, results: string): Promise<bigint>;
    createPosition(portfolioId: bigint, asset: string, buyPrice: number, quantity: number, signalStrength: SignalStrength): Promise<bigint>;
    createReadyToDumpSignal(symbol: string, timeframe: string, signalStrength: SignalStrength, confidenceScore: number, entryZone: number, takeProfitZone: number, stopLossZone: number): Promise<bigint>;
    createStrategy(name: string, description: string, performance: string, code: string): Promise<bigint>;
    createTradeJournalEntry(positionId: bigint, outcome: string, notes: string, exitTime: Time | null, pnl: number): Promise<bigint>;
    deleteBacktest(backtestId: bigint): Promise<void>;
    deletePosition(positionId: bigint): Promise<void>;
    deleteReadyToDumpSignal(signalId: bigint): Promise<void>;
    deleteStrategy(strategyId: bigint): Promise<void>;
    deleteTradeJournalEntry(entryId: bigint): Promise<void>;
    fetchCryptoDataFromBinance(): Promise<string>;
    getActiveReadyToDumpSignals(): Promise<Array<ReadyToDumpSignal>>;
    getAllBacktests(): Promise<Array<Backtest>>;
    getAllPositions(): Promise<Array<Position>>;
    getAllReadyToDumpSignals(): Promise<Array<ReadyToDumpSignal>>;
    getAllStrategies(): Promise<Array<Strategy>>;
    getAllTradeJournalEntries(): Promise<Array<TradeJournalEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDefaultSettings(): Promise<Settings>;
    getPositionsByPortfolio(portfolioId: bigint): Promise<Array<Position>>;
    getStrategy(id: bigint): Promise<Strategy | null>;
    getStrategyCode(id: bigint): Promise<string | null>;
    getUserBacktests(): Promise<Array<Backtest>>;
    getUserPositions(): Promise<Array<Position>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSettings(): Promise<Settings>;
    getUserStrategies(): Promise<Array<Strategy>>;
    getUserTradeJournalEntries(): Promise<Array<TradeJournalEntry>>;
    isCallerAdmin(): Promise<boolean>;
    resetUserSettings(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveUserSettings(settings: Settings): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBacktest(backtestId: bigint, performance: string, results: string): Promise<void>;
    updatePosition(positionId: bigint, sellPrice: number | null, stopLoss: number | null, takeProfit: number | null): Promise<void>;
    updateReadyToDumpSignal(signalId: bigint, timeframe: string, signalStrength: SignalStrength, confidenceScore: number, entryZone: number, takeProfitZone: number, stopLossZone: number): Promise<void>;
    updateStrategy(strategyId: bigint, name: string, description: string, performance: string, code: string): Promise<void>;
    updateTradeJournalEntry(entryId: bigint, outcome: string, notes: string, exitTime: Time | null, pnl: number): Promise<void>;
}
import type { Backtest as _Backtest, Position as _Position, ReadyToDumpSignal as _ReadyToDumpSignal, SignalStrength as _SignalStrength, Strategy as _Strategy, Time as _Time, TradeJournalEntry as _TradeJournalEntry, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBacktest(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBacktest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBacktest(arg0, arg1, arg2);
            return result;
        }
    }
    async createPosition(arg0: bigint, arg1: string, arg2: number, arg3: number, arg4: SignalStrength): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPosition(arg0, arg1, arg2, arg3, to_candid_SignalStrength_n3(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPosition(arg0, arg1, arg2, arg3, to_candid_SignalStrength_n3(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createReadyToDumpSignal(arg0: string, arg1: string, arg2: SignalStrength, arg3: number, arg4: number, arg5: number, arg6: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReadyToDumpSignal(arg0, arg1, to_candid_SignalStrength_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReadyToDumpSignal(arg0, arg1, to_candid_SignalStrength_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createStrategy(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createStrategy(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStrategy(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createTradeJournalEntry(arg0: bigint, arg1: string, arg2: string, arg3: Time | null, arg4: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTradeJournalEntry(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTradeJournalEntry(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async deleteBacktest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBacktest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBacktest(arg0);
            return result;
        }
    }
    async deletePosition(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePosition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePosition(arg0);
            return result;
        }
    }
    async deleteReadyToDumpSignal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReadyToDumpSignal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReadyToDumpSignal(arg0);
            return result;
        }
    }
    async deleteStrategy(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStrategy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStrategy(arg0);
            return result;
        }
    }
    async deleteTradeJournalEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTradeJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTradeJournalEntry(arg0);
            return result;
        }
    }
    async fetchCryptoDataFromBinance(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCryptoDataFromBinance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCryptoDataFromBinance();
            return result;
        }
    }
    async getActiveReadyToDumpSignals(): Promise<Array<ReadyToDumpSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveReadyToDumpSignals();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveReadyToDumpSignals();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBacktests(): Promise<Array<Backtest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBacktests();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBacktests();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPositions(): Promise<Array<Position>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPositions();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPositions();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReadyToDumpSignals(): Promise<Array<ReadyToDumpSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReadyToDumpSignals();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReadyToDumpSignals();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStrategies(): Promise<Array<Strategy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStrategies();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStrategies();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTradeJournalEntries(): Promise<Array<TradeJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTradeJournalEntries();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTradeJournalEntries();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDefaultSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultSettings();
            return result;
        }
    }
    async getPositionsByPortfolio(arg0: bigint): Promise<Array<Position>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPositionsByPortfolio(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPositionsByPortfolio(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStrategy(arg0: bigint): Promise<Strategy | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStrategy(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStrategy(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStrategyCode(arg0: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStrategyCode(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStrategyCode(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBacktests(): Promise<Array<Backtest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBacktests();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBacktests();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPositions(): Promise<Array<Position>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPositions();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPositions();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return result;
        }
    }
    async getUserStrategies(): Promise<Array<Strategy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStrategies();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStrategies();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTradeJournalEntries(): Promise<Array<TradeJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTradeJournalEntries();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTradeJournalEntries();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resetUserSettings(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetUserSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetUserSettings();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveUserSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserSettings(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBacktest(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBacktest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBacktest(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePosition(arg0: bigint, arg1: number | null, arg2: number | null, arg3: number | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePosition(arg0, to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePosition(arg0, to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateReadyToDumpSignal(arg0: bigint, arg1: string, arg2: SignalStrength, arg3: number, arg4: number, arg5: number, arg6: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReadyToDumpSignal(arg0, arg1, to_candid_SignalStrength_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReadyToDumpSignal(arg0, arg1, to_candid_SignalStrength_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateStrategy(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStrategy(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStrategy(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateTradeJournalEntry(arg0: bigint, arg1: string, arg2: string, arg3: Time | null, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTradeJournalEntry(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTradeJournalEntry(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
function from_candid_Backtest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Backtest): Backtest {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Position_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ReadyToDumpSignal_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReadyToDumpSignal): ReadyToDumpSignal {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SignalStrength_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalStrength): SignalStrength {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Strategy_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Strategy): Strategy {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TradeJournalEntry_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeJournalEntry): TradeJournalEntry {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Strategy]): Strategy | null {
    return value.length === 0 ? null : from_candid_Strategy_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: Principal;
    createdAt: _Time;
    results: string;
    updatedAt: [] | [_Time];
    performance: string;
    strategyId: bigint;
}): {
    id: bigint;
    userId: Principal;
    createdAt: Time;
    results: string;
    updatedAt?: Time;
    performance: string;
    strategyId: bigint;
} {
    return {
        id: value.id,
        userId: value.userId,
        createdAt: value.createdAt,
        results: value.results,
        updatedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.updatedAt)),
        performance: value.performance,
        strategyId: value.strategyId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    portfolioId: bigint;
    signalStrength: _SignalStrength;
    asset: string;
    userId: Principal;
    takeProfit: [] | [number];
    sellPrice: [] | [number];
    stopLoss: [] | [number];
    buyPrice: number;
    quantity: number;
}): {
    id: bigint;
    portfolioId: bigint;
    signalStrength: SignalStrength;
    asset: string;
    userId: Principal;
    takeProfit?: number;
    sellPrice?: number;
    stopLoss?: number;
    buyPrice: number;
    quantity: number;
} {
    return {
        id: value.id,
        portfolioId: value.portfolioId,
        signalStrength: from_candid_SignalStrength_n9(_uploadFile, _downloadFile, value.signalStrength),
        asset: value.asset,
        userId: value.userId,
        takeProfit: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.takeProfit)),
        sellPrice: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.sellPrice)),
        stopLoss: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.stopLoss)),
        buyPrice: value.buyPrice,
        quantity: value.quantity
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    code: string;
    userId: [] | [Principal];
    name: string;
    description: string;
    performance: string;
}): {
    id: bigint;
    code: string;
    userId?: Principal;
    name: string;
    description: string;
    performance: string;
} {
    return {
        id: value.id,
        code: value.code,
        userId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.userId)),
        name: value.name,
        description: value.description,
        performance: value.performance
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    pnl: number;
    exitTime: [] | [_Time];
    entryTime: _Time;
    userId: Principal;
    positionId: bigint;
    notes: string;
    outcome: string;
}): {
    id: bigint;
    pnl: number;
    exitTime?: Time;
    entryTime: Time;
    userId: Principal;
    positionId: bigint;
    notes: string;
    outcome: string;
} {
    return {
        id: value.id,
        pnl: value.pnl,
        exitTime: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.exitTime)),
        entryTime: value.entryTime,
        userId: value.userId,
        positionId: value.positionId,
        notes: value.notes,
        outcome: value.outcome
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    riskTolerance: [] | [number];
    preferredTimeframe: [] | [string];
    name: string;
}): {
    riskTolerance?: number;
    preferredTimeframe?: string;
    name: string;
} {
    return {
        riskTolerance: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.riskTolerance)),
        preferredTimeframe: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.preferredTimeframe)),
        name: value.name
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    stopLossZone: number;
    entryZone: number;
    signalStrength: _SignalStrength;
    timeframe: string;
    createdAt: _Time;
    takeProfitZone: number;
    confidenceScore: number;
    updatedAt: [] | [_Time];
    symbol: string;
}): {
    id: bigint;
    stopLossZone: number;
    entryZone: number;
    signalStrength: SignalStrength;
    timeframe: string;
    createdAt: Time;
    takeProfitZone: number;
    confidenceScore: number;
    updatedAt?: Time;
    symbol: string;
} {
    return {
        id: value.id,
        stopLossZone: value.stopLossZone,
        entryZone: value.entryZone,
        signalStrength: from_candid_SignalStrength_n9(_uploadFile, _downloadFile, value.signalStrength),
        timeframe: value.timeframe,
        createdAt: value.createdAt,
        takeProfitZone: value.takeProfitZone,
        confidenceScore: value.confidenceScore,
        updatedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.updatedAt)),
        symbol: value.symbol
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    strongBuy: null;
} | {
    hold: null;
} | {
    sell: null;
} | {
    strongSell: null;
}): SignalStrength {
    return "buy" in value ? SignalStrength.buy : "strongBuy" in value ? SignalStrength.strongBuy : "hold" in value ? SignalStrength.hold : "sell" in value ? SignalStrength.sell : "strongSell" in value ? SignalStrength.strongSell : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Backtest>): Array<Backtest> {
    return value.map((x)=>from_candid_Backtest_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Position>): Array<Position> {
    return value.map((x)=>from_candid_Position_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Strategy>): Array<Strategy> {
    return value.map((x)=>from_candid_Strategy_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeJournalEntry>): Array<TradeJournalEntry> {
    return value.map((x)=>from_candid_TradeJournalEntry_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReadyToDumpSignal>): Array<ReadyToDumpSignal> {
    return value.map((x)=>from_candid_ReadyToDumpSignal_n7(_uploadFile, _downloadFile, x));
}
function to_candid_SignalStrength_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalStrength): _SignalStrength {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    riskTolerance?: number;
    preferredTimeframe?: string;
    name: string;
}): {
    riskTolerance: [] | [number];
    preferredTimeframe: [] | [string];
    name: string;
} {
    return {
        riskTolerance: value.riskTolerance ? candid_some(value.riskTolerance) : candid_none(),
        preferredTimeframe: value.preferredTimeframe ? candid_some(value.preferredTimeframe) : candid_none(),
        name: value.name
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalStrength): {
    buy: null;
} | {
    strongBuy: null;
} | {
    hold: null;
} | {
    sell: null;
} | {
    strongSell: null;
} {
    return value == SignalStrength.buy ? {
        buy: null
    } : value == SignalStrength.strongBuy ? {
        strongBuy: null
    } : value == SignalStrength.hold ? {
        hold: null
    } : value == SignalStrength.sell ? {
        sell: null
    } : value == SignalStrength.strongSell ? {
        strongSell: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
